postgres_proj:
  outputs:
    dev:
      dbname: project-db
      host: host.docker.internal
      pass: password1
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: charry
  target: dev
